### ISSUE TITLE
Combined_Saria64_OOT on hardware

### ISSUE THREAD

**Issue by Jeville** [hylian-modding/Z64-CustomPlayerModels#87]
![saria](https://user-images.githubusercontent.com/40967133/185512161-7b587a24-9dc9-486a-8c7c-0c406b0f6333.png)
![saria2](https://user-images.githubusercontent.com/40967133/185513959-85d5ecb9-0a50-4626-9dd7-6bfb5bd2c99d.png)

Triangles with gaps.

**Comment by denoflionsx** [comment]
This repository is for Oot Online/MM Online and as such we do not test on
hardware. I'll pass this along to the actual modeler but it's up them if
they care to try and do anything about it.

**Comment by Maplesstar** [comment]
This is because rando implemention has some bugs, especially with models created on the new pipeline. Please in the future check this list to know what models are currently not working on hardware: https://docs.google.com/spreadsheets/d/1xbJnYw8lGR_qAkpvOQXlzvSUobWdX6phTm1SRbXy4TQ/edit#gid=1223582726
(I know this issue is a few months old but commenting here just in case someone else tries to bug you guys about this in the future maybe they'll see this)
